export const ACCESS_TOKEN = 'ACCESS_TOKEN'
export const ACTIVITY_TYPES = 'ACTIVITY_TYPES'
export const ACTIVITY_APPLICABLES = 'ACTIVITY_APPLICABLES'
export const PRIVILEGES = 'PRIVILEGES'

export const LOADING = 'LOADING'
export const CMS_MODELS = 'CMS_MODELS'
export const CMS_CHANNELS = 'CMS_CHANNELS'
export const CMS_CHANNEL_CHILDREN = 'CMS_CHANNEL_CHILDREN'
export const CMS_PARENT_CHANNEL = 'CMS_PARENT_CHANNEL'
export const CMS_CURRENT_CHANNEL = 'CMS_CURRENT_CHANNEL'
export const CMS_CONTENTS = 'CMS_CONTENTS'

export const  PRIVILEGE_CURRENT_ROLE = 'PRIVILEGE_CURRENT_ROLE'
