<?php

use Illuminate\Database\Seeder;

class SniperEmployeePositionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sniper_employee_positions')->delete();
        
        \DB::table('sniper_employee_positions')->insert(array (
            0 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-08 18:00:11',
                'deleted_at' => NULL,
                'department_id' => 116359451,
                'depth' => 0,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 1,
                'jd' => '服务全公司的那谁',
                'left' => 1,
                'name' => '总经理',
                'parent_id' => NULL,
                'right' => 30,
                'updated_at' => '2020-09-25 15:15:47',
            ),
            1 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-08 18:01:18',
                'deleted_at' => NULL,
                'department_id' => 116375321,
                'depth' => 1,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 2,
                'jd' => NULL,
                'left' => 2,
                'name' => '产品研发部主管',
                'parent_id' => 1,
                'right' => 15,
                'updated_at' => '2020-09-27 15:45:09',
            ),
            2 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-08 18:02:23',
                'deleted_at' => NULL,
                'department_id' => 116375322,
                'depth' => 2,
                'desiring' => 2,
                'highAbility' => NULL,
                'id' => 3,
                'jd' => NULL,
                'left' => 3,
                'name' => '电子学开发组组长',
                'parent_id' => 2,
                'right' => 4,
                'updated_at' => '2020-09-24 10:53:11',
            ),
            3 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-09 18:06:00',
                'deleted_at' => NULL,
                'department_id' => 116375314,
                'depth' => 1,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 6,
                'jd' => '人事大总管',
                'left' => 16,
                'name' => '人力主管',
                'parent_id' => 1,
                'right' => 19,
                'updated_at' => '2020-09-25 15:15:47',
            ),
            4 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-09 18:06:23',
                'deleted_at' => NULL,
                'department_id' => 116375314,
                'depth' => 2,
                'desiring' => 2,
                'highAbility' => NULL,
                'id' => 7,
                'jd' => '招人啊',
                'left' => 17,
                'name' => '人事',
                'parent_id' => 6,
                'right' => 18,
                'updated_at' => '2020-09-21 10:40:08',
            ),
            5 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-09 18:39:50',
                'deleted_at' => NULL,
                'department_id' => 6,
                'depth' => 1,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 8,
                'jd' => '库管',
                'left' => 20,
                'name' => '采购主管',
                'parent_id' => 1,
                'right' => 21,
                'updated_at' => '2020-09-25 15:15:47',
            ),
            6 => 
            array (
                'affordAbility' => '1',
                'basicAbility' => '1',
                'created_at' => '2020-09-21 10:37:17',
                'deleted_at' => NULL,
                'department_id' => 116375323,
                'depth' => 2,
                'desiring' => 1,
                'highAbility' => '1',
                'id' => 9,
                'jd' => '1',
                'left' => 5,
                'name' => '软件组组长',
                'parent_id' => 2,
                'right' => 6,
                'updated_at' => '2020-10-12 18:07:13',
            ),
            7 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-21 10:37:42',
                'deleted_at' => NULL,
                'department_id' => 116375326,
                'depth' => 2,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 10,
                'jd' => NULL,
                'left' => 7,
                'name' => '测试组长',
                'parent_id' => 2,
                'right' => 8,
                'updated_at' => '2020-09-27 18:43:55',
            ),
            8 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-21 10:38:03',
                'deleted_at' => NULL,
                'department_id' => 116375327,
                'depth' => 2,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 11,
                'jd' => NULL,
                'left' => 9,
                'name' => '加工组长',
                'parent_id' => 2,
                'right' => 10,
                'updated_at' => '2020-09-21 10:38:03',
            ),
            9 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-21 10:38:43',
                'deleted_at' => NULL,
                'department_id' => 116425477,
                'depth' => 2,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 12,
                'jd' => NULL,
                'left' => 11,
                'name' => '机械设计组长',
                'parent_id' => 2,
                'right' => 12,
                'updated_at' => '2020-09-21 10:38:43',
            ),
            10 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-21 10:40:08',
                'deleted_at' => NULL,
                'department_id' => 141958379,
                'depth' => 2,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 13,
                'jd' => NULL,
                'left' => 13,
                'name' => '中试组长',
                'parent_id' => 2,
                'right' => 14,
                'updated_at' => '2020-09-21 10:40:08',
            ),
            11 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-21 10:41:32',
                'deleted_at' => NULL,
                'department_id' => 116375312,
                'depth' => 1,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 14,
                'jd' => NULL,
                'left' => 22,
                'name' => '财务经理',
                'parent_id' => 1,
                'right' => 23,
                'updated_at' => '2020-09-25 15:15:47',
            ),
            12 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-21 10:42:19',
                'deleted_at' => NULL,
                'department_id' => 116375315,
                'depth' => 1,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 15,
                'jd' => NULL,
                'left' => 24,
                'name' => '采购经理',
                'parent_id' => 1,
                'right' => 25,
                'updated_at' => '2020-09-25 15:15:47',
            ),
            13 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-21 10:43:27',
                'deleted_at' => NULL,
                'department_id' => 116375316,
                'depth' => 1,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 16,
                'jd' => NULL,
                'left' => 26,
                'name' => '市场部经理',
                'parent_id' => 1,
                'right' => 27,
                'updated_at' => '2020-09-25 15:15:47',
            ),
            14 => 
            array (
                'affordAbility' => NULL,
                'basicAbility' => NULL,
                'created_at' => '2020-09-21 10:44:09',
                'deleted_at' => NULL,
                'department_id' => 126292488,
                'depth' => 1,
                'desiring' => 1,
                'highAbility' => NULL,
                'id' => 17,
                'jd' => NULL,
                'left' => 28,
                'name' => '生产部经理',
                'parent_id' => 1,
                'right' => 29,
                'updated_at' => '2020-09-25 15:15:47',
            ),
        ));
        
        
    }
}