import {fetch} from "./fetch"

export default {
    login: (data) => { return fetch("auth/login", data, 'post') },
    logout: (data) => { return fetch("auth/logout", data, 'post') },
    getCmsModels: (data) => { return fetch("/admin/cms/model", data) },
    getCmsChannelTree: (data) => { return fetch("/admin/cms/channel/tree", data) },
    getCmsChannelChildren: (data) => { return fetch("/admin/cms/channel/children", data) },
    getUserPermissions: (data) => { return fetch("/admin/privileges/user/permissions", data) },
    saveModelFieldType: (data) => { return fetch("/admin/cms/model/field/type/save", data, 'post') },
    getModelFieldTypes: (data) => { return fetch("/admin/cms/model/field/types", data) },
    deleteCmsChannel: (data) => { return fetch("/admin/cms/channel/delete", data, 'post') },
    saveCmsChannel: (data) => { return fetch("/admin/cms/channel/save", data, 'post') },
    getCmsChannelWhole: (data) => { return fetch("/admin/cms/channel/whole", data) },
    getCmsPositions: (data) => { return fetch("/admin/cms/positions", data) },
    createRoleUser: (data) => { return fetch("/admin/user/create/role/user", data, 'post') },
    removeRoleModel: (data) => { return fetch("/admin/privileges/remove/role/model", data, 'post') },
    saveRole: (data) => { return fetch("/admin/privileges/save/role", data, 'post') },
    getRoles: (data) => { return fetch("/admin/privileges/roles", data) },
    getSubPositions: (data) => { return fetch("/admin/cms/position/subs", data, 'post') },
    savePosition: (data) => { return fetch("/admin/cms/position/save", data, 'post') },
    givePermissionsTo: (data) => { return fetch("/admin/privileges/give/permissions/to", data, 'post') },
    getPermissionsTree: (data) => { return fetch("/admin/privileges/permissions/tree", data) },
    getRolePermissions: (data) => { return fetch("/admin/privileges/role/permissions", data) },
    addPermission: (data) => { return fetch("/admin/privileges/add/permission", data, 'post') },
    editPermission: (data) => { return fetch("/admin/privileges/edit/permission", data, 'post') },
    deletePermission: (data) => { return fetch("/admin/privileges/delete/permission", data, 'post') },
    deleteContent: (data) => { return fetch("/admin/cms/content/delete", data, 'post') },
    saveContent: (data) => { return fetch("/admin/cms/content/save", data, 'post') },
    getModel: (data) => { return fetch("/admin/cms/model/get", data) },
    getChannelContents: (data) => { return fetch("/admin/cms/contents", data) },
    getWholeContent: (data) => { return fetch("/admin/cms/content/whole", data) },
    getContentPositions: (data) => { return fetch("/admin/cms/content/positions", data) },
    deleteModel: (data) => { return fetch("/admin/cms/model/delete", data, 'post') },
    addFieldType: (data) => { return fetch("/admin/cms/model/field/type/add", data, 'post') },
    getModels: (data) => { return fetch("/admin/cms/model", data) },
    saveModelFieldOrder: (data) => { return fetch("/admin/cms/model/save/field/order", data, 'post') },
    deleteModelField: (data) => { return fetch("/admin/cms/model/delete/field", data, 'post') },
    saveModel: (data) => { return fetch("/admin/cms/model/save", data, 'post') },
    modelSaveField: (data) => { return fetch("/admin/cms/model/save/field", data, 'post') },
    getPositionContents: (data) => { return fetch("/admin/cms/position/contents", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },
    xx: (data) => { return fetch("", data) },

}